### ISSUE TITLE
[FR] - Support Folia

### ISSUE THREAD

**Issue by cygbs** [Lorias-Jak/LoriTime#177]
Folia is a new Minecraft server software developed by PaperMC and is a fork of Paper. My server is currently running Folia, so I hope you can make the LoriTime plugin support it.

Thank you very much!

**Comment by Lorias-Jak** [comment]
Thank you for the suggestion! Currently I have not the amount of time to add support for another Plattform, as my Dance Cup is near. 
Regardless, I will have a look into it, when I got the time. I wanted to support paper fully, so folia will not be that much of additions or changes

**Comment by cygbs** [comment]
I also appreciate your willingness to consider supporting Folia. Today I thought of Folia as a fork for Paper, so I thought maybe adding 'folia supported: true' to 'plugin. yml' might make it work, but it failed.

```
[17:21:22 ERROR]: Error occurred while enabling LoriTimeBukkit v1.5.0 (Is it up to date?)
java.lang.UnsupportedOperationException: null
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.handle(CraftScheduler.java:524) ~[luminol-1.21.1.jar:1.21.1-DEV-770e4b8]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:252) ~[luminol-1.21.1.jar:1.21.1-DEV-770e4b8]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:239) ~[luminol-1.21.1.jar:1.21.1-DEV-770e4b8]
        at LoriTimeBukkit-1.5.0.jar/com.jannik_kuehn.loritimebukkit.schedule.BukkitScheduleAdapter.scheduleAsync(BukkitScheduleAdapter.java:45) ~[LoriTimeBukkit-1.5.0.jar:?]
        at LoriTimeBukkit-1.5.0.jar/com.jannik_kuehn.common.module.updater.UpdateCheck.startCheck(UpdateCheck.java:90) ~[LoriTimeBukkit-1.5.0.jar:?]
        at LoriTimeBukkit-1.5.0.jar/com.jannik_kuehn.common.LoriTimePlugin.enableAsMaster(LoriTimePlugin.java:106) ~[LoriTimeBukkit-1.5.0.jar:?]
        at LoriTimeBukkit-1.5.0.jar/com.jannik_kuehn.common.LoriTimePlugin.enable(LoriTimePlugin.java:85) ~[LoriTimeBukkit-1.5.0.jar:?]
        at LoriTimeBukkit-1.5.0.jar/com.jannik_kuehn.loritimebukkit.LoriTimeBukkit.onEnable(LoriTimeBukkit.java:47) ~[LoriTimeBukkit-1.5.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[luminol-1.21.1.jar:1.21.1-DEV-770e4b8]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[luminol-1.21.1.jar:1.21.1-DEV-770e4b8]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:647) ~[luminol-1.21.1.jar:1.21.1-DEV-770e4b8]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:596) ~[luminol-1.21.1.jar:1.21.1-DEV-770e4b8]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:779) ~[luminol-1.21.1.jar:1.21.1-DEV-770e4b8]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:526) ~[luminol-1.21.1.jar:1.21.1-DEV-770e4b8]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:331) ~[luminol-1.21.1.jar:1.21.1-DEV-770e4b8]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1280) ~[luminol-1.21.1.jar:1.21.1-DEV-770e4b8]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:356) ~[luminol-1.21.1.jar:1.21.1-DEV-770e4b8]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

This is a server based on Folia (fork), but there are issues during loading and it cannot be used using the above methods. I have successfully used this modification method to make some plugins support Folia before, but obviously it is not applicable to LoriTime.

Because I mainly use Folia now, I really hope to see LoriTime support it. Thank you.

**Comment by Lorias-Jak** [comment]
Currently working on Folia support. But it seems like I cant compile Folia myself. Getting Gradle issues. I will inform you, if I have a working build

**Comment by Lorias-Jak** [comment]
You can grab the newest version here
https://modrinth.com/plugin/loritime/version/1.6.0

If there are anny issues pls share them in a new issue
